version: '2.1'

services:

  mq:
    image: ${IMAGE}:${IMAGE_VER}
    restart: always
    networks:
      - lan
    labels:
      - "traefik.enable=true"
      - "traefik.port=8222"
      - "traefik.frontend.rule=Host:${APP_SITE}"
      - "traefik.frontend.auth.basic=${AUTH}"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    expose:
      - 4222
      - 8222
      - 6222

networks:
  lan:
    external:
      name: ${DCAPE_NET}
