# This file will be joined with docker-compose.app.yml from dcape
# See https://github.com/dopos/dcape

services:
  # This service will extend code from dcape
  app:
    labels:
      - traefik.http.services.${APP_TAG}.loadbalancer.server.port=8222
    #    hostname: ${SERVICE_HOST}
    command: --http_port 8222
    #  --user ${USER_NAME} --pass ${USER_PASS}
    ports:
      - "${SERVICE_ADDR}:4222"
