# custom app config
# overrides DCAPE/apps/drone/dcape-app/docker-compose.yml

version: '2'

services:
  app:
    container_name: ${SERVICE_HOST}
    command: -m 8222 --store sql --sql_driver postgres
      --user ${USER_NAME} --pass ${USER_PASS}
    environment:
      - PGDATABASE
      - PGUSER
      - PGPASSWORD
      - PGHOST=db
      - PGSSLMODE=disable
    labels:
      - "traefik.http.services.${APP_TAG}.loadbalancer.server.port=8222"
    ports:
      - "${SERVICE_ADDR}:4222"
