# app custom Makefile

# Docker repo & image name without version
IMAGE    ?= nats-streaming
# Docker image version
IMAGE_VER?= 0.20.0-alpine3.12

# Hostname for external access
APP_SITE ?= nats.dev.lan
# App names (db/user name etc)
APP_NAME ?= nats

# Enable DB usage:
# * Add DB config part to .env.sample
# * Enable db* targets
# * make db-create inside .drone-default target
USE_DB   ?= yes

# Add user config part to .env.sample
ADD_USER ?= yes

# ------------------------------------------------------------------------------
# app custom config

SERVICE_HOST ?= $(APP_NAME)
SERVICE_ADDR ?= 127.0.0.1:4222
DB_INIT_SQL   = postgres.db.sql
# ------------------------------------------------------------------------------
# .env template (custom part)
# inserted in .env.sample via 'make config'
define CONFIG_CUSTOM
# ------------------------------------------------------------------------------
# app custom config, generated by make config
# db:$(USE_DB) user:$(ADD_USER)

# LAN-wide container hostname
SERVICE_HOST=$(SERVICE_HOST)

# ip:port for external access
SERVICE_ADDR=$(SERVICE_ADDR)

endef

# ------------------------------------------------------------------------------
# Find and include DCAPE/apps/drone/dcape-app/Makefile
DCAPE_COMPOSE   ?= dcape-compose
DCAPE_MAKEFILE  ?= $(shell docker inspect -f "{{.Config.Labels.dcape_app_makefile}}" $(DCAPE_COMPOSE))
ifeq ($(shell test -e $(DCAPE_MAKEFILE) && echo -n yes),yes)
  include $(DCAPE_MAKEFILE)
else
  include /opt/dcape-app/Makefile
endif
